### ISSUE TITLE
"U_feed_mat" is missing, with no default

### ISSUE THREAD

**Issue by ut-energy-institute** [MatthewHeun/Recca#2]
Hello, I'm getting the following error when running the `calc_io_mats ` function. 

```
Error in calc_A(R = R_mat, U = U_feed_mat, V = V_mat, q = q_vec, f = f_vec,  : 
  argument "U_feed_mat" is missing, with no default
```

It's difficult for me to provide any context to this error, as the code was given to me to use. However, several people have used this code without running into this error. I've tried using previous releases of Recca and get the same error.

**Comment by MatthewHeun** [comment]
In previous versions of `Recca`, the use matrix (U) was split into two pieces, U_EIOU representing energy industry own use and U_excl_EIOU representing everything else in the U matrix. This naming was cumbersome and awkward.

The latest version of `Recca`splits the U matrix into two pieces, U_EIOU and U_feed. U_EIOU is the same as before. U_feed is the same as U_excl_EIOU, but the name now reflects the fact that these flows are feedstocks for the energy processing stage in the column of the U matrix. The U_feed matrix should be exactly the same as the U_excl_EIOU matrix in every instance. Only the name has changed.

All the tests for Recca are passing after the name change. So the package is internally consistent. 

Although it is hard to tell without an example, I expect the error occurs because external code makes a matrix named U_excl_EIOU and `Recca` now assumes this matrix will be called `U_feed`.

If you have a minimum working example (MWE) that demonstrates the error, I will be very happy to assist with the debugging process.

**Comment by ut-energy-institute** [comment]
Thank you, I was able to fix the issue by using a previous release of Recca. I had tried this before, but apparently I didn't go back far enough. I'll close this issue now. Thanks again.

**Comment by MatthewHeun** [comment]
Glad you were able to resolve your issue. I try very hard to *not* introduce breaking changes. But sometimes (as in this case), there is good reason to make a change. 

In the long run, I hope that you can modifying your code and data frames to adapt to the few changes that arise in `Recca`.
